Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "simpleauth-vm"
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.provision "shell", path: "provision/provision.sh"
end